name: Deploy to AWS EC2

# Запускать экшен только при пуше в ветку main (или master)
on:
  push:
    branches:
      - main
      # Если твоя главная ветка называется master, раскомментируй строку ниже и удали main
      # - master 

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2, Pull Code and Restart Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # Команды, которые GitHub выполнит на твоем сервере AWS
          script: |
            cd ~/bots/ScheduleBot
            
            # Скачиваем последние изменения из GitHub
            git pull origin main
            
            # Пересобираем и перезапускаем Docker-контейнер
            sudo docker compose up -d --build
            
            # Удаляем старые ненужные образы (чтобы память на AWS не закончилась)
            sudo docker image prune -f